### ISSUE TITLE
[CY-4773] brakeman version issue

### ISSUE THREAD

**Issue by chaudhary** [codacy/codacy-brakeman#32]
Currently, the latest version is integrated with brakeman version 4.3.1
We want to upgrade brakeman to latest version i.e. 5.1.1

How can we upgrade this?
Codacy UI only provided a way to turn on/off the build-in tools and does not provide any way to upgrade it.

**Comment by machadoit** [comment]
Hi @chaudhary for the tools to be updated, they need to be updated on this docker wrapper. It is a work that we do more often on some tools than others, you are welcome to contribute with a PR if it is something that you would like to see to happen faster, it would be very welcome! Otherwise, we will eventually update it, but we don't have an ETA for it.

That said and answering your question, to update it, you can bump the Brakeman version on the [Gemfile](https://github.com/codacy/codacy-brakeman/blob/master/Gemfile), and follow the steps at https://github.com/codacy/codacy-brakeman#update-version-with-docs.

**Comment by franciscodua** [comment]
Brakeman is already up to date in Codacy Cloud

**Comment by franciscodua** [comment]
Hey @chaudhary 
Actually, we had to revert this change. The tool's license in more recent versions doesn't allow it to be used for commercial purposes. Therefore, we can bump it to a version higher than 4.3.1 (before the license change).
